import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Acme Rockets",
  description: "Generated by Wasami Martins",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen bg-slate-50 dark:bg-black dark:text-white">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
